config/routes.rb
Rails.application.routes.draw do
  root 'tweets#index'

  get '/tweets' => 'tweets#index', as: 'tweets'

  get '/tweets/new' => 'tweets#new', as: 'new_tweet'

  get 'tweets/:id' => 'tweets#show', as: 'tweet'

  get '/tweets/' => 'tweets#show'

  post '/tweets/' => 'tweets#create'

  get '/tweets/:id/edit' => 'tweets#edit', as: 'edit_tweet'

  patch '/tweet/:id' => 'tweets#update'

  delete '/tweet/:id' => 'tweets#destroy', as: 'destroy_tweet'

end

app/models/tweet.rb
class Tweet < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  def index
    @tweets = Tweet.all
  end

  def show
    @tweet = Tweet.find(params[:id])
  end

  def new
    @tweet = Tweet.new
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TwitterRails</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/tweets/index.html.erb
<h1>GIller</h1>


<h3><%= link_to 'Create New Tweet', new_tweet_path %></h3>

<% @tweets.each do |el| %>
<hr />
<h2><a href="/tweets/<%=el.id %>"><%= "@#{el.title}: #{el.description}" %></a></h2>
<% end %>

app/views/tweets/new.html.erb
<%  %>

app/views/tweets/show.html.erb
<h1><%= @tweet.title %></h1>
<h3><%= @tweet.description%></h3>